### PR TITLE
Symfony 3 Composer dependency fix

### PR DESCRIPTION
**Pull request by thpl**
When using Symfony 3, the dependencies for symfony/http-foundation and symfony/routing in version 2.2 result in a version conflict opposite symfony/symfony 3.0.

This fixes it.

### CODE REVIEW

**Comment by thpl** [comment]
Of course this breaks compatibility with the PHP 5.3 and 5.4 branches due to the symfony/symfony requirement for PHP >= 5.5.9.

**Comment by ProPheT777** [comment]
You should support both, stay compatible with 2.x and support 3.x, we won't be compatible with only 3.x since we only use 2 components in very simple way. 

```json
"symfony/http-foundation": "~2.2|~3.0"
```

**Comment by thpl** [comment]
Very good point, thank you for pointing this out.

I pushed some new commits that fix this.

**Comment by ProPheT777** [comment]
:+1: Thank you!

**Comment by cboden** [comment]
Thanks guys!

**Pull request merged**
