### PR TITLE
Allow IDE autocompletion for WampConnection decorator

### PR DESCRIPTION
**Pull request by rkok**
Helped me experiment with the [ChatRoom](https://github.com/cboden/Ratchet-examples/blob/master/src/Website/ChatRoom.php) example :)

### CODE REVIEW

**Comment by ProPheT777** [comment]
unfortunately it's not a good idea, ConnectionInterface have several implementations, so when the implementation is different, your IDE will auto complete with wrong values.

It's better to have no auto completion instead of wrong.

**Comment by rkok** [comment]
Understood, too bad.

**Comment by rkok** [comment]
Actually found a better way to still allow code completion:

    class MyApp implements WampServerInterface {
        /**
         * @param WampConnection $conn
         */
        public function onOpen(ConnectionInterface $conn) {

**Comment by cboden** [comment]
:+1:

**Pull request closed without merging**
