### PR TITLE
Configurable keep alive intervals

### PR DESCRIPTION
**Pull request by ikovalyov**

### CODE REVIEW

**Comment by cboden** [comment]
Thanks for your interest in wanting to import Ratchet @ikovalyov!

The `App` class is meant to be an shortcut and opinionated class to save 90% of someone's requirements instead of having to piece together everything themselves. That being said I want to keep its method signatures to a minimum. 

That being said currently a user isn't able to change the keep alive timeout. I think a better approach would be to move the `enableKeepAlive` calls inside `route` to inside the if statements where WsServer is decorating the `$controller`. This would still set a 30 second default timer if nothing was specified but allow the user to pass a customized `WsServer` instance to `route` with their desired timer set. 

Let me know if you'd like to update this PR to tackle that or if I should create one.

**Comment by ikovalyov** [comment]
Hi.
I'll try to prepare new PR this week.
Thanks.

**Comment by ikovalyov** [comment]
Hi.
I added keepAliveEnabled check to make sure Timer won't be added few times.
Also I moved keepAliveTimeout  setting to the contructor of the WsServer with default value 30.
Also enableKeepAlive moved to the next line of the WsServer creation as you asked.
Please let me know if everything is ok.
Thanks.

**Comment by ikovalyov** [comment]
@cboden

**Comment by cboden** [comment]
Thanks for the update. The change to App.php is perfect. Could you undo the changes to WsServer.php though? With just the changes to App.php a developer would be able to do this:
```php
$loop = new React\EventLoop\Factory::create();
$app = new Ratchet\App('localhost', 8080, '0.0.0.0', $loop);
$echo = new Ratchet\WebSocket\WsServer(new Ratchet\Server\EchoServer);
$echo->enableKeepAlive($loop, 60);
$app->route('/echo', $echo);
```

Since the timeout can't work without an EventLoop I don't think it makes sense to separate the timeout input from the keepAlive method. It could give the wrong impression to a developer that if they configure timeout in WsServer construct it would just work.

**Comment by ikovalyov** [comment]
done

**Comment by cboden** [comment]
Merged. Thanks @ikovalyov!

**Pull request merged**
