### PR TITLE
Add Symfony 6 support

### PR DESCRIPTION
**Pull request by frank9999**

### CODE REVIEW

**Comment by cboden** [comment]
Can you rebase your branch against the v0.4.4 branch please? This _should_ fix the failing tests.

**Comment by frank9999** [comment]
@cboden done! Can you approve the workflow so the pipeline can run?

**Comment by cboden** [comment]
> @cboden done! Can you approve the workflow so the pipeline can run?

Yessir!

**Comment by simPod** [comment]
@frank9999 VirtualSessionStorage does not comply with SF6 signature so now it seems broken 🤔

**Pull request merged**
