### PR TITLE
Binary message support

### LINKED ISSUE #18: Binary support
Part of #13 is including binary message support for the WS protocol. 

I'm thinking this will expand on the WebSocketComponent interface addax an _onFile_ method. Try to further incorporate SF2 HttpFoundation by passing a _File_ object to the method.

### PR DESCRIPTION
**Pull request by cboden**
Fixes #18, #393

### CODE REVIEW

**Comment by ProPheT777** [comment]
:+1: Good job! :tada:

**Comment by whimsicaldreamer** [comment]
How can we use this now?

**Comment by cboden** [comment]
Pull in the 0.4 branch with composer. Checkout the [autobahn script](https://github.com/ratchetphp/Ratchet/blob/0.4/tests/autobahn/bin/fuzzingserver.php) to see it using binary messages. Notice that you're given a Message object instead of a raw string now.

**Comment by whimsicaldreamer** [comment]
Ok. So should I remove "cboden/ratchet": "0.3.*" from require in composer and add 0.4 instead or should I add it along with 0.3.*?

**Comment by cboden** [comment]
Yes. `0.4-dev` as it hasn't been released yet. Be aware there are some BC breaks in the upcoming version such as the HTTP interface change documented in #427.

**Comment by whimsicaldreamer** [comment]
Yes for which one?
Am sorry am relatively new to these.

**Comment by cboden** [comment]
Instead of. Use the following command to install/upgrade:
```bash
composer require cboden/ratchet:0.4.x-dev
```

**Comment by subins2000** [comment]
Hey !

    The 0.4 branch doesn't seem to have binary support anymore ? Why was it removed ?

**Comment by cboden** [comment]
I just re-uploaded the binary branch. I thought I had merged it into the 0.4 branch already but guess I hadn't.

**Comment by cboden** [comment]
Never mind...the 0.4 branch does have binary support. Instead of passing a string in `onMessage` a [Message instance](https://github.com/ratchetphp/RFC6455/blob/master/src/Messaging/MessageInterface.php) is passed instead.

**Comment by mengnalin90** [comment]
Hi it seems that the binary part is not working now. When I tried to send binary data back to client side, it got failed with "failed: Could not decode a text frame as UTF-8."
Maybe I got smoothing wrong.

**Comment by subins2000** [comment]
@mengnalin90 Here is how I did it. Use this to send binary messages :
```php
$client->send(new Ratchet\RFC6455\Messaging\Frame($msg->getPayload(), true, Frame::OP_BINARY));
```

**Pull request merged**
