### PR TITLE
Fix http keep connection support

### PR DESCRIPTION
**Pull request by shellus**
TCP multiplexing support

### CODE REVIEW

**Comment by cboden** [comment]
Can you elaborate on what this does?

**Comment by shellus** [comment]
Thanks for the reply, please see https://en.wikipedia.org/wiki/HTTP_persistent_connection

**Comment by shellus** [comment]
Use the chrome browser to access the Ratchet HttpServer application. If you press F5 to refresh the page continuously. Some requests will be very slow, because the browser default TCP connection can be reused, but in fact Ratchet HttpServer does not support TCP connections for reuse.

**Comment by cboden** [comment]
I don't think this is possible with WebSockets. Once the connection has been upgraded from HTTP to WebSocket both the client and server are expected to speak the RFC6455 protocol until the connection is closed or one peer sends a CLOSE frame at which point one of the peers is to close the connection.

**Comment by shellus** [comment]
This commit does not affect WebSocket

**Comment by cboden** [comment]
The failing unit tests suggest otherwise  :)

**Comment by shellus** [comment]
I'm sorry, I know, I'll fix it

**Comment by shellus** [comment]
Whether to give me some tips, how should I let HttpServer support HTTP http keep

**Comment by shellus** [comment]
My day, that's it

```
    public function onOpen(ConnectionInterface $conn) {
        $conn->httpHeadersReceived = false;
    }
```
Just in the `onOpen`` $ conn-> httpHeadersReceived = false; `, you can achieve what I need


I'm sorry to have trouble you

**Comment by shellus** [comment]
```
    public function onOpen(\Ratchet\ConnectionInterface $conn, \Guzzle\Http\Message\RequestInterface $request = null)
    {

        $body = 'ok' . ++$this->requestCounter;
        $response = new \Guzzle\Http\Message\Response(200,null,$body);

        $response->setHeader('Content-Length', strlen($body));
        $response->setHeader('Connection', 'Keep-Alive');

        $conn->send((string)$response);
        $conn->httpHeadersReceived = false;

        if ($request->getHeader('Connection')->hasValue('close')){
            $conn->close();
        }
    }
```
$ ab -t 60 -c 20 -r -k http://127.0.0.1:8000/
This is ApacheBench, Version 2.3 <$Revision: 1748469 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)
Completed 5000 requests
Completed 10000 requests
Completed 15000 requests
Completed 20000 requests
Completed 25000 requests
Completed 30000 requests
Completed 35000 requests
Completed 40000 requests
Completed 45000 requests
Completed 50000 requests


Server Software:
Server Hostname:        127.0.0.1
Server Port:            8000

Document Path:          /
Document Length:        7 bytes

Concurrency Level:      20
Time taken for tests:   13.216 seconds
Complete requests:      50000
Failed requests:        0
Keep-Alive requests:    50000
Total transferred:      3450000 bytes
HTML transferred:       350000 bytes
Requests per second:    3783.29 [#/sec] (mean)
Time per request:       5.286 [ms] (mean)
Time per request:       0.264 [ms] (mean, across all concurrent requests)
Transfer rate:          254.93 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.0      0       5
Processing:     0    5   1.7      5      56
Waiting:        0    5   1.7      5      56
Total:          0    5   1.7      5      56

Percentage of the requests served within a certain time (ms)
  50%      5
  66%      5
  75%      5
  80%      5
  90%      6
  95%     10
  98%     10
  99%     10
 100%     56 (longest request)
Finished 50000 requests

```

```

**Pull request closed without merging**
