### PR TITLE
Allow Symfony 5

### PR DESCRIPTION
**Pull request by simPod**

### CODE REVIEW

**Comment by cboden** [comment]
I haven't kept up with Symfony 5 release documentation. Are there no API changes/breaks?

**Comment by Nek-** [comment]
Symfony is supposed to break indeed. But it looks like it doesn't impact ratchet.

I tested this patch:

```
git remote add simpod git@github.com:simPod/Ratchet.git
git fetch simpod
git checkout allow-symfony-5
composer install
```

With the following wstest config in `fuzzingclient.json`:
```json
{
   "outdir": "./reports/servers",
   "servers": [
      {
         "url": "ws://127.0.0.1:8000"
      }
   ],
   "cases": ["*"],
   "exclude-cases": [],
   "exclude-agent-cases": {}
}
```

```
php tests/autobahn/bin/fuzzingserver.php &
wstest -m fuzzingclient
```

Everything is green. (artifacts zipped joined)
[reports.zip](https://github.com/ratchetphp/Ratchet/files/3907218/reports.zip)

**Comment by simPod** [comment]
I also run in against static analysis and everything seems to be compatible

**Comment by WyriHaximus** [comment]
Considering it looks like it's covered by the tests I doubt there will be issues

**Comment by pyatnitsev** [comment]
Any news here?

**Comment by ricardoboss** [comment]
+1

**Comment by simPod** [comment]
Wow, neat!

**Comment by pyatnitsev** [comment]
I think, it’s a good point to make a release with that change.

**Comment by mbonneau** [comment]
v0.4.2 has been tagged - thanks!

**Comment by pyatnitsev** [comment]
@mbonneau, as I can see, there is small mistake - you're add version 0.4.2, but in the ConnectionInterface const version set to 'Ratchet/0.4.1'

**Pull request merged**
