### PR TITLE
Fix coding standards (PSR-1 and PSR-2 compatible)

### PR DESCRIPTION
**Pull request by hugohenrique**

### CODE REVIEW

**Comment by hugohenrique** [comment]
ping @cboden

**Comment by cboden** [comment]
What were the PSR-1 incompatibilities? I'm not a fan of PSR-2 having `{` on new lines for classes and functions...

**Comment by hugohenrique** [comment]
I used [php-cs-fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer)

**Comment by hugohenrique** [comment]
I added the PSR2 to be used on all great projects that I know.
@cboden, this PR will be accepted? Or should I close?

**Comment by cboden** [comment]
Sorry for the lack of feedback. As I'm not big on the `{` newline  I won't be merging this as it is right now.

**Pull request closed without merging**
